In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import sys

In [8]:
import numpy as np
import sys

a = np.array([1,2,3])
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

#print matrix
print(a)
print(b)

#get dimension
print("Dimension", a.ndim)
print("Dimesnion", b.ndim)

#get type/size
print("Type", a.dtype, "Size", a.itemsize, "bytes")
print("Type", b.dtype, "Size", b.itemsize, "bytes")

#shape
print(a.shape)
print(b.shape)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]
Dimension 1
Dimesnion 2
Type int32 Size 4 bytes
Type float64 Size 8 bytes
(3,)
(2, 3)


In [12]:
#get total size
print(a.size * a.itemsize)
print(b.size * b.itemsize)

print(a.nbytes)
print(b.nbytes)

12
48
12
48


In [14]:
#Accessing/Changing specific elements, rows, columns, etc

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a.shape

(2, 7)

In [22]:
#get a specific element [row, col]

#for accessing 4
print(a[0,3])
print(a[0, -4])

#for accessing 12
print(a[1, 4])
print(a[1, -3])

4
4
12
12


In [25]:
#get a specific row
print(a[0, :])
print(a[1, :])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [28]:
#get a specific column
print(a[:, 2])
print(a[:, 4])

[ 3 10]
[ 5 12]


In [30]:
#getting a little more fancy [startIndex:endIndex:stepSize]
print(a[0,1:6:2])

[2 4 6]


In [31]:
#for changing elements
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [33]:
#3-D example

b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
#get specific element(work outside in)
print(b[0,1,1])

4


In [35]:
print(b[:,1,:])

[[3 4]
 [7 8]]


In [36]:
#replace
b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [41]:
#initializing different types of arrays


#all 0s matrix

#1-D array
print(np.zeros(5))

#2-D array
print(np.zeros((2,3)))

#3-D array
print(np.zeros((2,3,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [43]:
#all 1s matrix

#1-D array
print(np.ones(5))

#2-D array
print(np.ones((4,2)))

#3-D array
print(np.ones((4,2,3)))

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [46]:
#any other number

print(np.full((2,2), 99))

[[99 99]
 [99 99]]


In [48]:
#any other number (full_like)

np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
#random decimal numbers
print(np.random.rand(4,2))
print(np.random.rand(4,2,3))

print(np.random.random_sample(a.shape))

[[0.76101202 0.15132763]
 [0.45186426 0.49913713]
 [0.74742943 0.18558736]
 [0.46334001 0.24212948]]
[[[0.07094684 0.67905341 0.99817038]
  [0.47060959 0.10407532 0.45787417]]

 [[0.5755861  0.46189683 0.47696434]
  [0.60066977 0.07078998 0.97040574]]

 [[0.64924998 0.35459443 0.70606871]
  [0.34234737 0.78443296 0.82747852]]

 [[0.20426758 0.75547551 0.34893647]
  [0.82348517 0.91746072 0.87538227]]]
[[0.29738443 0.42416316 0.36487795 0.76765643 0.94115997 0.0835704
  0.5527503 ]
 [0.56543446 0.25231811 0.39575322 0.92993495 0.12447124 0.78757348
  0.44851326]]


In [54]:
#random integer values

#if there is only single number then it will be excluded in making of the array
print(np.random.randint(7, size=(3,3)))

#if there are two numbers then the 1st number is taken as starting number in the array and the second is excluded
print(np.random.randint(-4,8, size=(3,3)))

[[2 5 0]
 [1 3 5]
 [4 6 0]]
[[ 2  4  4]
 [-3  2 -3]
 [ 6  2 -3]]


In [57]:
#the identity matrix

print(np.identity(3))

print(np.identity(5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [59]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3) #second paramter is treated as now many times the each number should be repeated
print(r1)

[1 1 1 2 2 2 3 3 3]


In [61]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [67]:
#Mathematics

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [68]:
#add
print(a + 2)

[3 4 5 6]


In [69]:
#subtract
print(a - 2)

[-1  0  1  2]


In [70]:
#multiply
print(a * 2)

[2 4 6 8]


In [71]:
#division
print(a / 2)

[0.5 1.  1.5 2. ]


In [73]:
b = np.array([1,0,1,0])

In [74]:
a + b

array([4, 4, 6, 6])

In [75]:
a - b

array([2, 4, 4, 6])

In [76]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [77]:
#take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [78]:
#take the cosine
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [82]:
#Linear algebra

a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [83]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [85]:
#Statistics

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(stats)

1

In [87]:
np.max(stats)

6

In [88]:
np.min(stats, axis=0)

array([1, 2, 3])

In [91]:
np.max(stats, axis=1)

array([3, 6])

In [93]:
np.sum(stats)

21

In [95]:
np.sum(stats, axis=1)

array([ 6, 15])

In [99]:
#Reorganizing arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)


after = before.reshape((4,2))
print(after)

after = before.reshape((8,1))
print(after)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [100]:
#Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
#Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])